-- TOPLAM SATIÞ TUTARI
SELECT SUM(OD.QUANTITY*OD.UNITPRICE) AS TOTALSALES
FROM ORDERDETAILS AS OD;

--TOPLAM SÝPARÝÞ SAYISI
SELECT COUNT(*) TOTALORDERS
FROM ORDERS;

--TOPLAM SATILAN ÜRÜN ADEDÝ
SELECT SUM(QUANTITY) TOTALQUANTITYSOLD
FROM ORDERDETAILS ;

-- ORTALAMA SÝPARÝÞ TUTARI
SELECT 
    AVG(ORDERTOTAL) AS AVERAGEORDERVALUE
FROM
(
    SELECT 
        O.ORDERID,
        SUM(OD.QUANTITY * OD.UNITPRICE) AS ORDERTOTAL
    FROM ORDERS O
    JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
    GROUP BY O.ORDERID
)AS AV ;

--EN YÜKSEK TUTARLI SÝPARÝÞLER
SELECT 
    O.ORDERID,
    C.CUSTOMERNAME,
    O.ORDERDATE,
    SUM(OD.QUANTITY * OD.UNITPRICE) AS ORDERTOTAL
FROM ORDERS O
JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID
JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
GROUP BY O.ORDERID, C.CUSTOMERNAME, O.ORDERDATE
ORDER BY ORDERTOTAL DESC;

--EN ÇOK SATILAN ÜRÜNLER
SELECT 
    P.PRODUCTNAME,
    SUM(OD.QUANTITY) AS TOTALQUANTITYSOLD
FROM ORDERDETAILS OD
JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
GROUP BY P.PRODUCTNAME
ORDER BY TOTALQUANTITYSOLD DESC;

--EN ÇOK GELÝR GETÝREN ÜRÜNLER
SELECT 
    P.PRODUCTNAME,
    SUM(OD.QUANTITY * OD.UNITPRICE) AS TOTALREVENUE
FROM ORDERDETAILS OD
JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
GROUP BY P.PRODUCTNAME
ORDER BY TOTALREVENUE DESC;

-- KATEGORÝ BAZLI SATIÞ ANALÝZÝ 
SELECT 
    CAT.CATEGORYNAME,
    SUM(OD.QUANTITY * OD.UNITPRICE) AS TOTALSALES
FROM ORDERDETAILS OD
JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
JOIN CATEGORIES CAT ON P.CATEGORYID = CAT.CATEGORYID
GROUP BY CAT.CATEGORYNAME
ORDER BY TOTALSALES DESC;

-- KATEGORÝ BAZLI SATILAN ÜRÜN ADEDÝ
SELECT 
    CAT.CATEGORYNAME,
    SUM(OD.QUANTITY) AS TOTALQUANTITY
FROM ORDERDETAILS OD
JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
JOIN CATEGORIES CAT ON P.CATEGORYID = CAT.CATEGORYID
GROUP BY CAT.CATEGORYNAME
ORDER BY TOTALQUANTITY DESC;

-- EN DEÐERLÝ MÜÞTERÝLER
SELECT 
    C.CUSTOMERNAME,
    CI.CITYNAME,
    COUNT(DISTINCT O.ORDERID) AS ORDERCOUNT,
    SUM(OD.QUANTITY * OD.UNITPRICE) AS TOTALSPENT
FROM CUSTOMERS C
JOIN CITIES CI ON C.CITYID = CI.CITYID
JOIN ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
GROUP BY C.CUSTOMERNAME, CI.CITYNAME
ORDER BY TOTALSPENT DESC;

--ÞEHÝRLERE GÖRE SATIÞ ANALÝZÝ
SELECT 
    CI.CITYNAME,
    SUM(OD.QUANTITY * OD.UNITPRICE) AS TOTALSALES
FROM ORDERS O
JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID
JOIN CITIES CI ON C.CITYID = CI.CITYID
JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
GROUP BY CI.CITYNAME
ORDER BY TOTALSALES DESC;

-- AYLIK SATIÞ TRENDÝ
SELECT 
    YEAR(O.ORDERDATE) AS ORDERYEAR,
    MONTH(O.ORDERDATE) AS ORDERMONTH,
    SUM(OD.QUANTITY * OD.UNITPRICE) AS TOTALSALES
FROM ORDERS O
JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
GROUP BY YEAR(O.ORDERDATE), MONTH(O.ORDERDATE)
ORDER BY ORDERYEAR, ORDERMONTH;

-- YILLIK SATIÞ ANALÝZÝ 
SELECT 
    YEAR(O.ORDERDATE) AS ORDERYEAR,
    SUM(OD.QUANTITY * OD.UNITPRICE) AS TOTALSALES
FROM ORDERS O
JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
GROUP BY YEAR(O.ORDERDATE)
ORDER BY ORDERYEAR;

-- ÖDEME YÖNTEMÝNE GÖRE SATIÞ ANALÝZÝ
SELECT 
    O.PAYMENTMETHOD,
    COUNT(DISTINCT O.ORDERID) AS ORDERCOUNT,
    SUM(OD.QUANTITY * OD.UNITPRICE) AS TOTALSALES
FROM ORDERS O
JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
GROUP BY O.PAYMENTMETHOD
ORDER BY TOTALSALES DESC;

-- YAÞ GRUPLARINA GÖRE SATIÞ ANALÝZÝ
SELECT 
    CASE 
        WHEN C.AGE BETWEEN 18 AND 25 THEN '18-25'
        WHEN C.AGE BETWEEN 26 AND 35 THEN '26-35'
        WHEN C.AGE BETWEEN 36 AND 45 THEN '36-45'
        ELSE '46+'
    END AS AGEGROUP,
    COUNT(DISTINCT O.ORDERID) AS ORDERCOUNT,
    SUM(OD.QUANTITY * OD.UNITPRICE) AS TOTALSALES
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
GROUP BY 
    CASE 
        WHEN C.AGE BETWEEN 18 AND 25 THEN '18-25'
        WHEN C.AGE BETWEEN 26 AND 35 THEN '26-35'
        WHEN C.AGE BETWEEN 36 AND 45 THEN '36-45'
        ELSE '46+'
    END
ORDER BY TOTALSALES DESC;